###########
# site.title

title:    'The Wizard'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-cayman
